name: app
description: A new flutter application project.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_database: ^1.0.5
  firebase_auth: ^0.6.6
  shared_preferences: any
  share: ^0.5.3
  material_design_icons_flutter: ^3.0.3392
  flutter_svg: ^0.10.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

